### ISSUE TITLE
'Undefined' variable issue in refactor.js

### ISSUE THREAD

**Issue by luismetzger** [gregbrunk/tic-tac-toe#2]
I noticed an issue with your variables in your 'Board' class. This could be due to calling the body instead of the document? 

(see screenshot)

http://prntscr.com/bkn4m2

**Comment by gregbrunk** [comment]
I believe this is resolved, I am no longer getting this error. 

<img width="1135" alt="screen shot 2016-06-26 at 4 31 57 pm" src="https://cloud.githubusercontent.com/assets/19507409/16365377/986ca8be-3bbb-11e6-8307-1ec280f66dc1.png">
